name: Coverage Upload

on:
    push:
        paths:
            - "**.rs"
            - "**rust-coverage-ci.yml"

env:
    CARGO_TERM_COLOR: always

jobs:
    coverage-lib:
        runs-on: ubuntu-latest
        steps:
            - name: Update Rust
              run: rustup update stable
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Use dependencies cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-coverage-
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: Install cargo-nextest
              uses: taiki-e/install-action@nextest
            - name: Generate code coverage
              run: cargo llvm-cov nextest --all-features --workspace --codecov --output-path codecov-lib.json --no-cfg-coverage --ignore-filename-regex ".*/puzzle-cube-ui/.*"
            - name: Coverage Upload for Lib
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./codecov-lib.json
                  flags: lib
                  fail_ci_if_error: true

    coverage-ui:
        runs-on: ubuntu-latest
        steps:
            - name: Update Rust
              run: rustup update stable
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Use dependencies cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-coverage-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-coverage-
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: Install cargo-nextest
              uses: taiki-e/install-action@nextest
            - name: Generate code coverage
              run: cargo llvm-cov nextest --all-features --workspace --codecov --output-path codecov-ui.json --no-cfg-coverage --ignore-filename-regex ".*/puzzle-cube/.*"
            - name: Coverage Upload for UI
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./codecov-ui.json
                  flags: ui
                  fail_ci_if_error: true
